
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vrajp
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String currentSemester;
    private String author;
    private String project;

    public MainFrame() {
        initComponents();
        checkData();
        rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
        rebuildCourseComboBoxes();
        rebuildSelectClassComboBoxes();
    }

        public void rebuildSemesterComboBoxes() {
            ArrayList<String> semesters = SemesterQueries.getSemesterList();
            currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
            if (semesters.size() > 0) {
                currentSemesterLabel.setText(semesters.get(0));
                currentSemester = semesters.get(0);
            } else {
                currentSemesterLabel.setText("None, add a semester.");
                currentSemester = "None";
            }
        }

        public void rebuildStudentComboBoxes() {
            ArrayList<StudentEntry> studentEntries = StudentQueries.getAllStudents();
            ArrayList<String> students = new ArrayList<>();
            for (int i = 0; i < studentEntries.size(); i++) {
                students.add(studentEntries.get(i).getLastName() + "," + studentEntries.get(i).getFirstName());
            }
            addSelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
            addSelectStudentComboBox2.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
            addDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
            addStudentDropClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
            }
            
        public void rebuildCourseComboBoxes(){
            ArrayList<String> courseCodes = CourseQueries. getAllCourseCodes(currentSemester);
            addCourseCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray()));
            addDisplayClassListComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray()));
            addDropClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray()));
            addStudentChooseClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray()));
       
        }
         
        public void rebuildSelectClassComboBoxes() {
            ArrayList<String> courseCodes = ClassQueries.getAllCourseCodes(currentSemester);
            addSelectClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray()));
            addSelectClassComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray()));
    
            }
            
        public String removeFromWaitlist(String status, String courseCode) {
        ArrayList<ScheduleEntry> waitlist = ScheduleQueries.getWaitlistedStudentsByClass(currentSemester, courseCode);
        String waitlistStudentString = "";
        if (status.equals("S") && !waitlist.isEmpty()) {
            StudentEntry waitListStudent = StudentQueries.getStudent(waitlist.get(0).getStudentID());
            ScheduleEntry newEntry = new ScheduleEntry(currentSemester, courseCode, waitListStudent.getStudentID(), "S",new java.sql.Timestamp(System.currentTimeMillis()));
            ScheduleQueries.updateScheduleEntry(currentSemester,newEntry);
            waitlistStudentString = "\n" + waitListStudent.getLastName() + "," + waitListStudent.getFirstName() + " " + waitListStudent.getStudentID() + " has been scheduled into " + courseCode;
        }
        return waitlistStudentString;
        }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        addDropStudent = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addCourseCodeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addCourseDescriptionTextField = new javax.swing.JTextField();
        addCourseSubmitButton = new javax.swing.JButton();
        addCourseStatusLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addStudentIDTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addFirstNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addLastNameTextField = new javax.swing.JTextField();
        addStudentStatusLabel = new javax.swing.JLabel();
        addStudentSubmitButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addCourseCodeComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        addSeatsSpinner = new javax.swing.JSpinner();
        addClassButton = new javax.swing.JButton();
        addClassStatusLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        addChooseClass = new javax.swing.JLabel();
        addDisplayClassListComboBox = new javax.swing.JComboBox<>();
        addDisplayClassListButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayClassListTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addDisplayClassListTable2 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        addChooseStudent = new javax.swing.JLabel();
        addDropStudentComboBox = new javax.swing.JComboBox<>();
        addDropStudentButton = new javax.swing.JButton();
        addDropStudentTextField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        addDropClassComboBox = new javax.swing.JComboBox<>();
        addDropClassSubmit = new javax.swing.JButton();
        addDropClassTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addStudentDropClass = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        addDisplayClassesButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        addDisplayClassesTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        addSelectClassComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        addSelectStudentComboBox = new javax.swing.JComboBox<>();
        addScheduleClassButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        addScheduleClassLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        addSelectStudentComboBox2 = new javax.swing.JComboBox<>();
        addDisplayStudentScheduleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addDisplayStudentScheduleTable = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        addStudentDropClassComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        addStudentChooseClassComboBox = new javax.swing.JComboBox<>();
        addStudentDropClassStudentSubmit = new javax.swing.JButton();
        StudentDropClassTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");

        jLabel3.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addSemesterSubmitButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        addDropStudent.addTab("Add Semester", jPanel3);

        jLabel4.setText("Course Code:");

        addCourseCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseCodeTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Course Description: ");

        addCourseSubmitButton.setText("Submit");
        addCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseSubmitButtonActionPerformed(evt);
            }
        });

        addCourseStatusLabel.setText("       ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseSubmitButton)
                            .addComponent(addCourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addCourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCourseSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCourseStatusLabel)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        addDropStudent.addTab("Add Course", jPanel4);

        jLabel6.setText("Student ID:");

        addStudentIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentIDTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("First Name: ");

        addFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFirstNameTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Last Name: ");

        addStudentStatusLabel.setText("      ");

        addStudentSubmitButton.setText("Submit");
        addStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(addStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addFirstNameTextField))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addStudentSubmitButton)
                                .addComponent(addLastNameTextField))))
                    .addComponent(addStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(addStudentSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStudentStatusLabel)
                .addGap(0, 293, Short.MAX_VALUE))
        );

        addDropStudent.addTab("Add Student", jPanel6);

        jLabel9.setText("Course Code: ");

        addCourseCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addCourseCodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseCodeComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Seats:");

        addClassButton.setText("Submit");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        addClassStatusLabel.setText("          ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(addCourseCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addClassButton)
                            .addComponent(addSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addClassStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addCourseCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addClassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addClassStatusLabel)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        addDropStudent.addTab("Add Class", jPanel7);

        addChooseClass.setText("Choose Class:");

        addDisplayClassListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addDisplayClassListButton.setText("Display");
        addDisplayClassListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisplayClassListButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Scheduled Students in the Class: ");

        DisplayClassListTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ));
        jScrollPane2.setViewportView(DisplayClassListTable1);

        jLabel16.setText("Waitlisted Students in the Class in Waitlist Order: ");

        addDisplayClassListTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ));
        jScrollPane4.setViewportView(addDisplayClassListTable2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(addChooseClass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDisplayClassListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(addDisplayClassListButton))
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addChooseClass)
                    .addComponent(addDisplayClassListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDisplayClassListButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        addDropStudent.addTab("Display Class List", jPanel10);

        addChooseStudent.setText("Choose Student: ");

        addDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addDropStudentButton.setText("Submit");
        addDropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDropStudentButtonActionPerformed(evt);
            }
        });

        addDropStudentTextField.setText("   ");
        addDropStudentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDropStudentTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addDropStudentButton)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(addChooseStudent)
                            .addGap(18, 18, 18)
                            .addComponent(addDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addDropStudentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addChooseStudent)
                    .addComponent(addDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addDropStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDropStudentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        addDropStudent.addTab("Drop Student", jPanel11);

        jLabel17.setText("Choose Class: ");

        addDropClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addDropClassComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addDropClassComboBoxItemStateChanged(evt);
            }
        });

        addDropClassSubmit.setText("Submit");
        addDropClassSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDropClassSubmitActionPerformed(evt);
            }
        });

        addDropClassTextField.setText("    ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDropClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(addDropClassSubmit))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addDropClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(addDropClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDropClassSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDropClassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        addDropStudent.addTab("Drop Class", jPanel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addDropStudent)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addDropStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        addDisplayClassesButton.setText("Display");
        addDisplayClassesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisplayClassesButtonActionPerformed(evt);
            }
        });

        addDisplayClassesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ));
        jScrollPane3.setViewportView(addDisplayClassesTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(addDisplayClassesButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDisplayClassesButton)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        addStudentDropClass.addTab("Display Classes", jPanel5);

        jLabel11.setText("Select Class:");

        addSelectClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addSelectClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelectClassComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setText("Select Student: ");

        addSelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addScheduleClassButton.setText("Submit");
        addScheduleClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScheduleClassButtonActionPerformed(evt);
            }
        });

        addScheduleClassLabel.setText("          ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addScheduleClassButton)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addSelectClassComboBox, 0, 148, Short.MAX_VALUE)
                                .addComponent(addSelectStudentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addScheduleClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(addSelectClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(addSelectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addScheduleClassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addScheduleClassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addStudentDropClass.addTab("Schedule Class", jPanel8);

        jLabel14.setText("Select Student:");

        addSelectStudentComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addSelectStudentComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelectStudentComboBox2ActionPerformed(evt);
            }
        });

        addDisplayStudentScheduleButton.setText("Display");
        addDisplayStudentScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisplayStudentScheduleButtonActionPerformed(evt);
            }
        });

        addDisplayStudentScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Status"
            }
        ));
        jScrollPane1.setViewportView(addDisplayStudentScheduleTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSelectStudentComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(addDisplayStudentScheduleButton)))
                .addGap(99, 204, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(addSelectStudentComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDisplayStudentScheduleButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        addStudentDropClass.addTab("Display Student Schedule", jPanel9);

        jLabel18.setText("Choose Student: ");

        addStudentDropClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Choose Class: ");

        addStudentChooseClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addStudentDropClassStudentSubmit.setText("Submit");
        addStudentDropClassStudentSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentDropClassStudentSubmitActionPerformed(evt);
            }
        });

        StudentDropClassTextField.setText("    ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addStudentDropClassStudentSubmit)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addStudentDropClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addStudentChooseClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentDropClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(addStudentDropClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(addStudentChooseClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addStudentDropClassStudentSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentDropClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        addStudentDropClass.addTab("Drop Class", jPanel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(addStudentDropClass, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(addStudentDropClass, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("Current Semester: ");

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeSemesterButton)
                                .addGap(31, 31, 31)
                                .addComponent(aboutButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton)
                    .addComponent(aboutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        // display about information.
        JOptionPane.showMessageDialog(null, "Author: " + author + " Project: " + project);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
        String semester = addSemesterTextfield.getText();
        SemesterQueries.addSemester(semester);
        addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterSubmitButtonActionPerformed

    private void addCourseCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseCodeTextFieldActionPerformed

    private void addCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseSubmitButtonActionPerformed
        // TODO add your handling code here:
        if (addCourseCodeTextField.getText().length() > 0 && addCourseDescriptionTextField.getText().length() > 0) {
            CourseEntry newCourseEntry = new CourseEntry(addCourseCodeTextField.getText(),addCourseDescriptionTextField.getText());
            CourseQueries.addCourse(newCourseEntry);
            addCourseStatusLabel.setText(addCourseCodeTextField.getText() + " has been added.");
            addCourseCodeComboBox.addItem(newCourseEntry.getCourseCode());
            addSelectClassComboBox.addItem(newCourseEntry.getCourseCode());
            addDisplayClassListComboBox.addItem(newCourseEntry.getCourseCode());
            addDropClassComboBox.addItem(newCourseEntry.getCourseCode());
            addStudentChooseClassComboBox.addItem(newCourseEntry.getCourseCode());
        }
        
    }//GEN-LAST:event_addCourseSubmitButtonActionPerformed

    private void addStudentIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentIDTextFieldActionPerformed

    private void addStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        if (addStudentIDTextField.getText().length() > 0 && addFirstNameTextField.getText().length() > 0 && addLastNameTextField.getText().length() > 0){
            StudentEntry newStudent = new StudentEntry(addStudentIDTextField.getText(), addFirstNameTextField.getText(), addLastNameTextField.getText());
            StudentQueries.addStudent(newStudent);
            addStudentStatusLabel.setText(addLastNameTextField.getText()+ ", " + addFirstNameTextField.getText() + " has been added");
            rebuildStudentComboBoxes();  
        }
    }//GEN-LAST:event_addStudentSubmitButtonActionPerformed

    private void addCourseCodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseCodeComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addCourseCodeComboBoxActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        // TODO add your handling code here:
        String semester = currentSemesterLabel.getText();
        String courseCode = addCourseCodeComboBox.getSelectedItem().toString();
        int seats = (int) addSeatsSpinner.getValue();
        ClassQueries.addClass(new ClassEntry(semester, courseCode, seats));
        addClassStatusLabel.setText(courseCode + " has been added to " + semester + " with " + seats + " seats ");
        rebuildSelectClassComboBoxes();
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void addSelectStudentComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelectStudentComboBox2ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_addSelectStudentComboBox2ActionPerformed

    private void addScheduleClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScheduleClassButtonActionPerformed
        // TODO add your handling code here
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();
        String semester = currentSemesterLabel.getText();
        String courseCode = addSelectClassComboBox.getSelectedItem().toString();

        // Check if the selected item is not null before calling toString()
        Object selectedStudentItem = addSelectStudentComboBox.getSelectedItem();
        String studentName = (selectedStudentItem != null) ? selectedStudentItem.toString() : "Unknown Student";

        String studentID = "Unknown ID"; // Default value
        if (selectedStudentItem != null) {
            int selectedIndex = addSelectStudentComboBox.getSelectedIndex();
            if (selectedIndex >= 0 && selectedIndex < students.size()) {
                studentID = students.get(selectedIndex).getStudentID();
            }
        }

        String status = "";

        if (ClassQueries.getClassSeats(currentSemesterLabel.getText(), courseCode) > ScheduleQueries.getScheduledStudentCount(semester, courseCode)) {
            status = "S";
            addScheduleClassLabel.setText(studentName + " scheduled for " + courseCode);
        } else {
            status = "W";
            addScheduleClassLabel.setText(studentName + " waitlisted for " + courseCode);
        }

        ScheduleEntry scheduleEntry = new ScheduleEntry(semester, courseCode, studentID, status, new java.sql.Timestamp(System.currentTimeMillis()));
        ScheduleQueries.addScheduleEntry(scheduleEntry);
    }//GEN-LAST:event_addScheduleClassButtonActionPerformed

    private void addFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFirstNameTextFieldActionPerformed

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        if (semesters.size() > 0)
        {
            currentSemesterLabel.setText(currentSemesterComboBox.getSelectedItem().toString());
            currentSemester = currentSemesterLabel.getText();
        }
        else
        {
            currentSemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void addDisplayClassesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisplayClassesButtonActionPerformed
        // TODO add your handling code here
        ArrayList<ClassDescription> classes = MultiTableQueries.getAllClassDescriptions(currentSemester);
        DefaultTableModel displayClassesModel = (DefaultTableModel) addDisplayClassesTable.getModel();
        displayClassesModel.setNumRows(0);
        for (ClassDescription C: classes) {
            Object[] data = new Object[3];
            data[0] = C.getCourseCode();
            data[1] = C.getDescription();
            data[2] = C.getSeats();   
            displayClassesModel.addRow(data);
        } 

    }//GEN-LAST:event_addDisplayClassesButtonActionPerformed

    private void addDisplayStudentScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisplayStudentScheduleButtonActionPerformed
        // TODO add your handling code here:
        int studentItem = addSelectStudentComboBox2.getSelectedIndex();
        ArrayList<StudentEntry> studentEntries = StudentQueries.getAllStudents();
        StudentEntry student = studentEntries.get(studentItem);
        ArrayList<ScheduleEntry> schedule = ScheduleQueries.getScheduleByStudent(currentSemester, student.getStudentID());
        DefaultTableModel displayScheduleModel = (DefaultTableModel) addDisplayStudentScheduleTable.getModel();
        displayScheduleModel.setNumRows(0);
        for (ScheduleEntry S: schedule) {
            Object[] data = new Object[2];
            data[0] = S.getStudentID();
            String status = S.getStatus();
            if ("S".equals(status)) {
                data[1] = "Scheduled";
            } else {
                data[1] = "Waitlisted";
            }
            displayScheduleModel.addRow(data);
            
        }
    
    }//GEN-LAST:event_addDisplayStudentScheduleButtonActionPerformed

    private void addSelectClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelectClassComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSelectClassComboBoxActionPerformed

    private void addDisplayClassListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisplayClassListButtonActionPerformed
        // TODO add your handling code here:
        String className = addDisplayClassListComboBox.getSelectedItem().toString();
        ArrayList<StudentEntry> scheduledStudents = MultiTableQueries.getScheduledStudentsByClass(currentSemester, className);
        ArrayList<StudentEntry> waitlistedStudents = MultiTableQueries.getWaitlistedStudentsByClass(currentSemester, className);
        DefaultTableModel displayScheduleModel = (DefaultTableModel) DisplayClassListTable1.getModel();
        DefaultTableModel displayWaitlistModel = (DefaultTableModel) addDisplayClassListTable2.getModel();
        displayScheduleModel.setNumRows(0);
        displayWaitlistModel.setNumRows(0);
        for (StudentEntry S: scheduledStudents) {
            Object[] data = new Object[3];
            data[0] = S.getLastName();
            data[1] = S.getFirstName();
            data[2] = S.getStudentID();
            
            displayScheduleModel.addRow(data);
        }
        
        for (StudentEntry W: waitlistedStudents) {
            Object[] data = new Object[3];
            data[0] = W.getLastName();
            data[1] = W.getFirstName();
            data[2] = W.getStudentID();
            
            displayWaitlistModel.addRow(data);
        }
    }//GEN-LAST:event_addDisplayClassListButtonActionPerformed

    private void addDropStudentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDropStudentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDropStudentTextFieldActionPerformed

    private void addDropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDropStudentButtonActionPerformed
        // TODO add your handling code here:
        addDropStudentTextField.setText("");
        String studentName = addDropStudentComboBox.getSelectedItem().toString();
        int studentItem = addDropStudentComboBox.getSelectedIndex();
        ArrayList<StudentEntry> studentEntries = StudentQueries.getAllStudents();
        StudentEntry dropStudent = studentEntries.get(studentItem);
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        
        String dropStudentString = "";
        
        dropStudentString = studentName + " " + dropStudent.getStudentID() + " has been dropped from the list of students." + "\n";
        
        for (String sem: semesters) {

            
            ArrayList<String> classes = ClassQueries.getAllCourseCodes(sem);
            
            dropStudentString += "For Semester: " + sem + "\n";
            for (String courseCode: classes) {
                
                ArrayList<ScheduleEntry> scheduleEntry = ScheduleQueries.getScheduleByStudent(sem, dropStudent.getStudentID());
                String status = "";
        
                for (ScheduleEntry S: scheduleEntry) {
                    
                    if (S.getCourseCode().equals(courseCode)) {
                        status = S.getStatus();
                        ScheduleQueries.dropStudentScheduleByCourse(sem, studentEntries.get(studentItem).getStudentID(), courseCode);
                        if (status.equals("W")) {
                            dropStudentString += studentName + " " + studentEntries.get(studentItem).getStudentID() + " has been dropped from the waitlist for " + courseCode + "\n";
                        } else {
                            dropStudentString += studentName + " " + studentEntries.get(studentItem).getStudentID() + " has been dropped from " + courseCode + "\n";
                        }
                        
                    }
                }

                
                ArrayList<ScheduleEntry> waitlist = ScheduleQueries.getWaitlistedStudentsByClass(sem, courseCode);

                String waitlistStudentString = "";
                if (status.equals("S") && !waitlist.isEmpty()) {
                    StudentEntry waitListStudent = StudentQueries.getStudent(waitlist.get(0).getStudentID());
                    ScheduleEntry newEntry = new ScheduleEntry(sem, courseCode, waitListStudent.getStudentID(), "S",new java.sql.Timestamp(System.currentTimeMillis()));
                    ScheduleQueries.updateScheduleEntry(currentSemester,newEntry);
                    waitlistStudentString = waitListStudent.getLastName() + "," + waitListStudent.getFirstName() + " " + waitListStudent.getStudentID() + " has been scheduled into " + courseCode + "\n";
                }
                
                dropStudentString += waitlistStudentString;
                
            }

        }
      StudentQueries.dropStudent(dropStudent.getStudentID());
      addDropStudentTextField.setText(dropStudentString);
      rebuildStudentComboBoxes();
    }//GEN-LAST:event_addDropStudentButtonActionPerformed

    private void addStudentDropClassStudentSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentDropClassStudentSubmitActionPerformed
        // TODO add your handling code here:
        String studentName = addStudentDropClassComboBox.getSelectedItem().toString();
        String courseCode = addStudentChooseClassComboBox.getSelectedItem().toString();
        int studentItem = addStudentDropClassComboBox.getSelectedIndex();
        ArrayList<StudentEntry> studentEntries = StudentQueries.getAllStudents();
        StudentEntry dropStudent = studentEntries.get(studentItem);
        ArrayList<ScheduleEntry> scheduleEntry = ScheduleQueries.getScheduleByStudent(currentSemester, dropStudent.getStudentID());
        
        String status = "";
        
        for (ScheduleEntry S: scheduleEntry) {
            if (S.getCourseCode().equals(courseCode)) {
                status = S.getStatus();
            }
        }

        ScheduleQueries.dropStudentScheduleByCourse(currentSemester, studentEntries.get(studentItem).getStudentID(), courseCode);
        String dropStudentString = studentName + " " + studentEntries.get(studentItem).getStudentID() + " has been dropped from " + courseCode;       

        ArrayList<ScheduleEntry> waitlist = ScheduleQueries.getWaitlistedStudentsByClass(currentSemester, courseCode);

        
        String waitlistStudentString = "";
        if (status.equals("S") && !waitlist.isEmpty()) {
            StudentEntry waitListStudent = StudentQueries.getStudent(waitlist.get(0).getStudentID());
            ScheduleEntry newEntry = new ScheduleEntry(currentSemester, courseCode, waitListStudent.getStudentID(), "S",new java.sql.Timestamp(System.currentTimeMillis()));
            ScheduleQueries.updateScheduleEntry(currentSemester,newEntry);
            waitlistStudentString = "\n" + waitListStudent.getLastName() + "," + waitListStudent.getFirstName() + " " + waitListStudent.getStudentID() + " has been scheduled into " + courseCode;
        }

        String finalString = dropStudentString + waitlistStudentString; 
        StudentDropClassTextField.setText(finalString);
    }//GEN-LAST:event_addStudentDropClassStudentSubmitActionPerformed

    private void addDropClassSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDropClassSubmitActionPerformed
        // TODO add your handling code here
        addDropClassTextField.setText("");
        String courseCode = addDropClassComboBox.getSelectedItem().toString();
        ClassQueries.dropClass(currentSemester, courseCode);

        ArrayList<StudentEntry> waitListStudents = MultiTableQueries.getWaitlistedStudentsByClass(currentSemester, courseCode);
        ArrayList<StudentEntry> schdueledStudents = MultiTableQueries.getScheduledStudentsByClass(currentSemester, courseCode);
        
        ScheduleQueries.dropScheduleByCourse(currentSemester, courseCode);
        String displayString = "Scheduled students dropped from the course:" + "\n";
        for (StudentEntry S: schdueledStudents) {
            displayString += S.getLastName() + "," + S.getFirstName() + " " + S.getStudentID() + "\n";
        }
        
        displayString += "Waitlisted students dropped from the course:" + "\n";
        for (StudentEntry W: waitListStudents) {
            displayString += W.getLastName() + "," + W.getFirstName() + " " + W.getStudentID() + "\n";
        }
        addDropClassTextField.setText(displayString);
        rebuildSelectClassComboBoxes();
    
    }//GEN-LAST:event_addDropClassSubmitActionPerformed

    private void addDropClassComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addDropClassComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addDropClassComboBoxItemStateChanged

    private void checkData() {
        try {
            FileReader reader = new FileReader("xzq789yy.txt");
            BufferedReader breader = new BufferedReader(reader);

            String encodedAuthor = breader.readLine();
            String encodedProject = breader.readLine();
            byte[] decodedAuthor = Base64.getDecoder().decode(encodedAuthor);
            author = new String(decodedAuthor);
            byte[] decodedProject = Base64.getDecoder().decode(encodedProject);
            project = new String(decodedProject);
            reader.close();

        } catch (FileNotFoundException e) {
            //get user info and create file
            author = JOptionPane.showInputDialog("Enter your first and last name.");
            project = "Course Scheduler Fall 2023";

            //write data to the data file.
            try {
                FileWriter writer = new FileWriter("xzq789yy.txt", true);
                BufferedWriter bufferedWriter = new BufferedWriter(writer);

                // encode the output data.
                String encodedAuthor = Base64.getEncoder().encodeToString(author.getBytes());

                bufferedWriter.write(encodedAuthor);
                bufferedWriter.newLine();

                String encodedProject = Base64.getEncoder().encodeToString(project.getBytes());
                bufferedWriter.write(encodedProject);

                bufferedWriter.close();
            } catch (IOException ioe) {
                ioe.printStackTrace();
                System.exit(1);
            }

        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisplayClassListTable1;
    private javax.swing.JTextField StudentDropClassTextField;
    private javax.swing.JButton aboutButton;
    private javax.swing.JLabel addChooseClass;
    private javax.swing.JLabel addChooseStudent;
    private javax.swing.JButton addClassButton;
    private javax.swing.JLabel addClassStatusLabel;
    private javax.swing.JComboBox<String> addCourseCodeComboBox;
    private javax.swing.JTextField addCourseCodeTextField;
    private javax.swing.JTextField addCourseDescriptionTextField;
    private javax.swing.JLabel addCourseStatusLabel;
    private javax.swing.JButton addCourseSubmitButton;
    private javax.swing.JButton addDisplayClassListButton;
    private javax.swing.JComboBox<String> addDisplayClassListComboBox;
    private javax.swing.JTable addDisplayClassListTable2;
    private javax.swing.JButton addDisplayClassesButton;
    private javax.swing.JTable addDisplayClassesTable;
    private javax.swing.JButton addDisplayStudentScheduleButton;
    private javax.swing.JTable addDisplayStudentScheduleTable;
    private javax.swing.JComboBox<String> addDropClassComboBox;
    private javax.swing.JButton addDropClassSubmit;
    private javax.swing.JTextField addDropClassTextField;
    private javax.swing.JTabbedPane addDropStudent;
    private javax.swing.JButton addDropStudentButton;
    private javax.swing.JComboBox<String> addDropStudentComboBox;
    private javax.swing.JTextField addDropStudentTextField;
    private javax.swing.JTextField addFirstNameTextField;
    private javax.swing.JTextField addLastNameTextField;
    private javax.swing.JButton addScheduleClassButton;
    private javax.swing.JLabel addScheduleClassLabel;
    private javax.swing.JSpinner addSeatsSpinner;
    private javax.swing.JComboBox<String> addSelectClassComboBox;
    private javax.swing.JComboBox<String> addSelectStudentComboBox;
    private javax.swing.JComboBox<String> addSelectStudentComboBox2;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JComboBox<String> addStudentChooseClassComboBox;
    private javax.swing.JTabbedPane addStudentDropClass;
    private javax.swing.JComboBox<String> addStudentDropClassComboBox;
    private javax.swing.JButton addStudentDropClassStudentSubmit;
    private javax.swing.JTextField addStudentIDTextField;
    private javax.swing.JLabel addStudentStatusLabel;
    private javax.swing.JButton addStudentSubmitButton;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
